<?php

/*
|--------------------------------------------------------------------------
| Job debug page
|--------------------------------------------------------------------------
*/

return [
    'title' => 'Job Debug',
    'subheading' => 'Last 50 jobs · Click a row for details.',
    'select_project' => 'Select project',

    'live' => [
        'on' => 'LIVE',
        'paused' => 'PAUSED',
        'pause_hint' => 'Pause live updates to read undisturbed',
        'resume_hint' => 'Resume live updates',
    ],

    'columns' => [
        'job' => 'Job',
        'status' => 'Status',
        'started' => 'Started',
        'duration' => 'Duration',
    ],

    'status' => [
        'success' => 'success',
        'failed' => 'failed',
        'running' => 'running…',
    ],

    'empty' => 'No jobs have run yet.',

    'detail' => [
        'heading' => 'Job #:id · :class',
        'close' => '✕ close',
        'tab_prompts' => 'Prompts (:count)',
        'tab_messages' => 'Messages (:count)',
        'prompt' => 'Prompt',
        'response' => 'Response',
        'no_prompts' => 'No prompts recorded for this job.',
        'no_messages' => 'No messages generated by this job.',
        'system_sender' => 'System',
    ],
];
